const loaderUtils = require('loader-utils')
const addQuery = require('../utils/add-query')
const normalize = require('../utils/normalize')
const parseRequest = require('../utils/parse-request')
const { matchCondition } = require('../utils/match-condition')
const templateCompiler = require('../template-compiler/compiler')
const { genTemplate } = require('../template-compiler/gen-node-react')
const bindThis = require('../template-compiler/bind-this')

module.exports = function (content) {
  const loaderContext = this
  const mpx = loaderContext.getMpx()

  const {
    projectRoot,
    mode,
    srcMode,
    env,
    defs,
    wxsContentMap,
    decodeHTMLText,
    externalClasses,
    forceProxyEventRules,
    getModuleId,
    rnConfig
  } = mpx

  const { resourcePath, rawResourcePath, queryObj } = parseRequest(loaderContext.resource)
  const moduleId = getModuleId(resourcePath)

  const warn = (msg, loc) => {
    loaderContext.emitWarning(
      new Error('[Mpx template warning][' + (loc || loaderContext.resourcePath) + ']: ' + msg)
    )
  }
  const error = (msg, loc) => {
    loaderContext.emitError(
      new Error('[Mpx template error][' + (loc || loaderContext.resourcePath) + ']: ' + msg)
    )
  }
  const parseOptions = {
    warn,
    error,
    mode,
    srcMode: queryObj.srcMode || srcMode,
    env,
    defs,
    decodeHTMLText,
    externalClasses,
    moduleId,
    filePath: rawResourcePath,
    forceProxyEvent: matchCondition(resourcePath, forceProxyEventRules),
    customBuiltInComponents: rnConfig && rnConfig.customBuiltInComponents
  }

  // Parse the template
  const { meta } = templateCompiler.parse(content, parseOptions)
  if (meta.wxsContentMap && wxsContentMap) {
    for (const module in meta.wxsContentMap) {
      wxsContentMap[`${rawResourcePath}~${module}`] = meta.wxsContentMap[module]
    }
  }

  // Generate imports
  const imports = []
  if (meta.imports) {
    const reactTemplateLoaderPath = normalize.lib('react/template-loader')
    meta.imports.forEach((importSrc) => {
      const request = loaderUtils.urlToRequest(importSrc, projectRoot)
      imports.push(`require(${loaderUtils.stringifyRequest(loaderContext, `!!${reactTemplateLoaderPath}!${request}`)})`)
    })
  }

  const builtInPaths = meta.builtInComponentsMap || {}
  const builtInComponents = []
  Object.keys(builtInPaths).forEach((componentName) => {
    const componentRequest = loaderUtils.stringifyRequest(loaderContext, addQuery(builtInPaths[componentName], { isComponent: true }))
    builtInComponents.push(`"${componentName}": function () { return getBuiltInBaseComponent(require(${componentRequest}), { __mpxBuiltIn: true }) }`)
  })

  // Generate local templates
  let localTemplatesCode = 'var localTemplates = {\n'
  if (meta.templates) {
    Object.keys(meta.templates).forEach((name) => {
      const template = meta.templates[name]
      const templateCode = genTemplate(template)
      if (templateCode) {
        localTemplatesCode += `${JSON.stringify(name)}: ${templateCode},\n`
      }
    })
  }
  localTemplatesCode += '};'

  try {
    const ignoreMap = Object.assign({
      createElement: true,
      getComponent: true,
      getTemplate: true
    }, meta.wxsModuleMap)
    const bindResult = bindThis.transform(localTemplatesCode, {
      ignoreMap
    })
    localTemplatesCode = bindResult.code
  } catch (e) {
    loaderContext.emitError(
      new Error(`[Mpx template error]: Invalid render function generated by the template, please check!\\n  Error code:\\n  ${localTemplatesCode}\\n  Error Detail:\\n  ${e.stack}`)
    )
  }

  let wxsImports = ''
  for (const module in meta.wxsModuleMap) {
    const request = loaderUtils.urlToRequest(meta.wxsModuleMap[module], projectRoot)
    wxsImports += `var ${module} = require(${loaderUtils.stringifyRequest(loaderContext, request)});\n`
  }
  const hasTemplateSource = imports.length || (meta.templates && Object.keys(meta.templates).length)
  const templateHelpersCode = hasTemplateSource
    ? `var templates = Object.assign({}, ${imports.join(', ') || '{}'});
    Object.assign(templates, localTemplates);
    function getTemplate(name) {
      return templates[name] || function(){};
    }`
    : ''

  const output = `
    ${wxsImports}
    var getBuiltInBaseComponent = require(${loaderUtils.stringifyRequest(loaderContext, normalize.lib('runtime/optionProcessorReact'))}).getComponent;
    var builtInComponentsMap = {${builtInComponents.join(',')}};
    ${localTemplatesCode}
    ${templateHelpersCode}
    function getBuiltInComponent(name) {
      var getter = builtInComponentsMap[name];
      return getter && getter();
    }
    function getTemplateComponent(name, getComponent) {
      return getComponent(name) || getBuiltInComponent(name);
    }
    Object.keys(localTemplates).forEach(function (name) {
      var template = localTemplates[name];
      localTemplates[name] = function (createElement, getComponent) {
        return template.call(this, createElement, function (componentName) {
          return getTemplateComponent(componentName, getComponent);
        });
      };
    });
    module.exports = localTemplates;
  `
  return output
}
