const loaderUtils = require('loader-utils')
const addQuery = require('../utils/add-query')
const normalize = require('../utils/normalize')
const parseRequest = require('../utils/parse-request')
const { matchCondition } = require('../utils/match-condition')
const templateCompiler = require('../template-compiler/compiler')
const { genTemplate } = require('../template-compiler/gen-node-react')
const bindThis = require('../template-compiler/bind-this')
const Template = require('webpack/lib/Template')

module.exports = function (content) {
  const loaderContext = this
  const mpx = loaderContext.getMpx()

  const {
    projectRoot,
    mode,
    srcMode,
    env,
    defs,
    wxsContentMap,
    decodeHTMLText,
    externalClasses,
    forceProxyEventRules,
    getModuleId
  } = mpx

  const { resourcePath, rawResourcePath, queryObj } = parseRequest(loaderContext.resource)
  const moduleId = getModuleId(resourcePath)

  const warn = (msg) => {
    loaderContext.emitWarning(
      new Error('[Mpx template warning][' + loaderContext.resource + ']: ' + msg)
    )
  }
  const error = (msg) => {
    loaderContext.emitError(
      new Error('[Mpx template error][' + loaderContext.resource + ']: ' + msg)
    )
  }
  const parseOptions = {
    warn,
    error,
    ctorType: 'template',
    mode,
    srcMode: queryObj.srcMode || srcMode,
    env,
    defs,
    decodeHTMLText,
    externalClasses,
    moduleId,
    filePath: rawResourcePath,
    forceProxyEvent: matchCondition(resourcePath, forceProxyEventRules)
  }

  // Parse the template
  const { meta } = templateCompiler.parse(content, parseOptions)
  if (meta.wxsContentMap && wxsContentMap) {
    for (const module in meta.wxsContentMap) {
      wxsContentMap[`${rawResourcePath}~${module}`] = meta.wxsContentMap[module]
    }
  }

  // Generate imports
  const imports = []
  if (meta.imports) {
    const reactTemplateLoaderPath = normalize.lib('react/template-loader')
    meta.imports.forEach((importSrc) => {
      const request = loaderUtils.urlToRequest(importSrc, projectRoot)
      imports.push(`require(${loaderUtils.stringifyRequest(loaderContext, `!!${reactTemplateLoaderPath}!${request}`)})`)
    })
  }

  const builtInComponents = []
  if (meta.builtInComponentsMap) {
    Object.keys(meta.builtInComponentsMap).forEach((componentName) => {
      const componentRequest = loaderUtils.stringifyRequest(loaderContext, addQuery(meta.builtInComponentsMap[componentName], { isComponent: true }))
      builtInComponents.push(`"${componentName}": function () { return getBuiltInBaseComponent(require(${componentRequest}), { __mpxBuiltIn: true }) }`)
    })
  }

  // Generate local templates
  let localTemplates = '{\n'
  if (meta.templates) {
    Object.keys(meta.templates).forEach((name) => {
      const template = meta.templates[name]
      const templateCode = genTemplate(template)
      // console.log('DEBUG: template', name, templateCode)
      if (templateCode) {
        try {
          const ignoreMap = Object.assign({
            createElement: true,
            getComponent: true,
            getTemplate: true
          }, meta.wxsModuleMap)
          const bindResult = bindThis.transform(templateCode, {
            ignoreMap
          })
          localTemplates += `${JSON.stringify(name)}: ${bindResult.code},\n`
        } catch (e) {
          loaderContext.emitError(
            new Error(`[Mpx template error]: Invalid render function generated by the template, please check!\n  Error code:\n  ${templateCode}\n  Error Detail:\n  ${e.stack}`)
          )
        }
      }
    })
  }
  localTemplates += '}'
  let wxsImports = ''
  for (const module in meta.wxsModuleMap) {
    const request = loaderUtils.urlToRequest(meta.wxsModuleMap[module], projectRoot)
    wxsImports += `var ${module} = require(${loaderUtils.stringifyRequest(loaderContext, request)});\n`
  }

  const output = `
    ${wxsImports}
    var getBuiltInBaseComponent = require(${loaderUtils.stringifyRequest(loaderContext, normalize.lib('runtime/optionProcessorReact'))}).getComponent;
    var builtInComponentsMap = {${builtInComponents.join(',')}};
    var templates = Object.assign({}, ${imports.join(', ') || '{}'});
    var localTemplates = ${localTemplates};
    Object.assign(templates, localTemplates);
    function getBuiltInComponent(name) {
      var getter = builtInComponentsMap[name];
      return getter && getter();
    }
    function getTemplateComponent(name, getComponent) {
      return getComponent(name) || getBuiltInComponent(name);
    }
    Object.keys(localTemplates).forEach(function (name) {
      var template = localTemplates[name];
      localTemplates[name] = function (createElement, getComponent) {
        return template.call(this, createElement, function (componentName) {
          return getTemplateComponent(componentName, getComponent);
        });
      };
    });
    function getTemplate(name) {
      return templates[name] || function(){};
    }
    module.exports = localTemplates;
  `
  return output
}
