language: node_js
node_js:
  - 11.3.0
before_install:
  - npm i
script:
  - npm run lint
before_deploy:
  - cd docs
  - npx gitbook-cli install
  - npx gitbook-cli build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN_LHY_MPX
  local_dir: docs/_book
  on:
    branch: master
