#!/usr/bin/env node
/**
 * Scans all exported methods from src/platform/api and generates
 * src/common/js/dynamic.js with lazy-loading require() wrappers.
 *
 * Run: node scripts/gen-dynamic.js
 */

const fs = require('fs')
const path = require('path')

const srcDir = path.resolve(__dirname, '../src')
const platformIndexPath = path.join(srcDir, 'platform/index.js')
const outputPath = path.join(srcDir, 'common/js/dynamic.js')
const commonJsDir = path.join(srcDir, 'common/js')

if (!fs.existsSync(platformIndexPath)) {
  console.error('platform/index.js not found:', platformIndexPath)
  process.exit(1)
}

const platformContent = fs.readFileSync(platformIndexPath, 'utf-8')

// Extract all "export * from './api/xxx'" paths
const exportMatches = [...platformContent.matchAll(/export \* from '(.+?)'/g)]

if (exportMatches.length === 0) {
  console.error('No export * from entries found in platform/index.js')
  process.exit(1)
}

// name -> requirePath (relative to common/js/)
const apiEntries = []
const seenNames = new Set()

for (const [, relPath] of exportMatches) {
  // relPath is like './api/system' or './api/device/network'
  const apiDir = path.join(srcDir, 'platform', relPath)

  let indexFilePaths
  if (fs.existsSync(apiDir) && fs.statSync(apiDir).isDirectory()) {
    // Merge exports from index.js and all platform variants such as index.web.js.
    indexFilePaths = fs.readdirSync(apiDir)
      .filter(fileName => /^index(?:\.[^.]+)?\.js$/.test(fileName))
      .map(fileName => path.join(apiDir, fileName))
  } else {
    // fallback: relPath might point directly to a .js file
    const fileName = path.basename(apiDir)
    const fileNameRegex = new RegExp(`^${fileName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}(?:\\.[^.]+)?\\.js$`)
    indexFilePaths = fs.readdirSync(path.dirname(apiDir))
      .filter(item => fileNameRegex.test(item))
      .map(item => path.join(path.dirname(apiDir), item))
  }

  if (indexFilePaths.length === 0) {
    console.warn('  [skip] entry file not found for:', relPath)
    continue
  }

  indexFilePaths.forEach(indexFilePath => {
    const content = fs.readFileSync(indexFilePath, 'utf-8')

    // Match all export { name1, name2, ... } blocks (may span multiple lines)
    const exportBlockRegex = /export\s*\{([^}]+)\}/g
    let blockMatch
    while ((blockMatch = exportBlockRegex.exec(content)) !== null) {
      const names = blockMatch[1]
        .split(',')
        .map(n => {
          // Handle "localName as exportedName" — take the exported name
          const parts = n.trim().split(/\s+as\s+/)
          return (parts[1] || parts[0]).trim()
        })
        .filter(n => n && /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(n))

      // require path: relative from common/js/ to the api dir's index (no .js extension)
      const requireTarget = path.join(apiDir, 'index')
      let requirePath = path.relative(commonJsDir, requireTarget).replace(/\\/g, '/')
      if (!requirePath.startsWith('.')) requirePath = './' + requirePath

      for (const name of names) {
        if (seenNames.has(name)) {
          continue
        }
        seenNames.add(name)
        apiEntries.push({ name, requirePath })
      }
    }
  })
}

if (apiEntries.length === 0) {
  console.error('No exported names found — aborting to avoid writing an empty file')
  process.exit(1)
}

// Build dynamic.js content
const methodLines = apiEntries.map(({ name, requirePath }, i) => {
  const comma = i < apiEntries.length - 1 ? ',' : ''
  return [
    `  ${name} (...args) {`,
    `    const ${name} = require('${requirePath}').${name}`,
    `    return ${name}(...args)`,
    `  }${comma}`
  ].join('\n')
})

const output = [
  '// This file is auto-generated by scripts/gen-dynamic.js — do not edit manually',
  'export default {',
  methodLines.join('\n'),
  '}',
  ''
].join('\n')

fs.writeFileSync(outputPath, output, 'utf-8')
console.log(`Generated ${path.relative(process.cwd(), outputPath)} with ${apiEntries.length} methods`)
